name: Build

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version-file: .tool-versions
      - run: uv sync
      - run: uv run python --version
      - run: uv run mypy --strict syzygy_tables_info
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - run: npm run lint
